// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type Credential struct {
	ID      []byte
	UserID  string
	Data    []byte
	Version int64
}

type Invitation struct {
	UserID     string
	SecretHash []byte
	Expires    int64
	Generation int64
}

type Login struct {
	ID           string
	UserID       string
	CredentialID []byte
	SecretHash   []byte
	Expires      int64
	Kind         string
	ClientID     string
}

type User struct {
	ID         string
	Name       string
	Disabled   int64
	Generation int64
}
