// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const clearInvitations = `-- name: ClearInvitations :exec
DELETE FROM invitations
`

func (q *Queries) ClearInvitations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearInvitations)
	return err
}

const clearLogins = `-- name: ClearLogins :exec
DELETE FROM logins
`

func (q *Queries) ClearLogins(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearLogins)
	return err
}

const consumeInvitation = `-- name: ConsumeInvitation :one
DELETE FROM invitations WHERE secret_hash = ? AND expires > ? AND user_id = ?
    AND generation = ? RETURNING user_id
`

type ConsumeInvitationParams struct {
	SecretHash []byte
	Expires    int64
	UserID     string
	Generation int64
}

func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, consumeInvitation,
		arg.SecretHash,
		arg.Expires,
		arg.UserID,
		arg.Generation,
	)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name) VALUES (?, ?) RETURNING id, name, disabled, generation
`

type CreateUserParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.Generation,
	)
	return i, err
}

const credentialLogins = `-- name: CredentialLogins :many
SELECT id FROM logins WHERE credential_id = ? AND user_id = ?
`

type CredentialLoginsParams struct {
	CredentialID []byte
	UserID       string
}

func (q *Queries) CredentialLogins(ctx context.Context, arg CredentialLoginsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, credentialLogins, arg.CredentialID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const credentials = `-- name: Credentials :many
SELECT id, user_id, data, version FROM credentials WHERE user_id = ? ORDER BY id
`

func (q *Queries) Credentials(ctx context.Context, userID string) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, credentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Data,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCredential = `-- name: DeleteCredential :execrows
DELETE FROM credentials WHERE id = ? AND user_id = ?
`

type DeleteCredentialParams struct {
	ID     []byte
	UserID string
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCredentials = `-- name: DeleteCredentials :exec
DELETE FROM credentials WHERE user_id = ?
`

func (q *Queries) DeleteCredentials(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteCredentials, userID)
	return err
}

const deleteInvitations = `-- name: DeleteInvitations :exec
DELETE FROM invitations WHERE user_id = ?
`

func (q *Queries) DeleteInvitations(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteInvitations, userID)
	return err
}

const deleteLogin = `-- name: DeleteLogin :one
DELETE FROM logins WHERE id = ? RETURNING user_id
`

func (q *Queries) DeleteLogin(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteLogin, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const expireInvitations = `-- name: ExpireInvitations :exec
DELETE FROM invitations WHERE expires <= ?
`

func (q *Queries) ExpireInvitations(ctx context.Context, expires int64) error {
	_, err := q.db.ExecContext(ctx, expireInvitations, expires)
	return err
}

const expireLogins = `-- name: ExpireLogins :exec
DELETE FROM logins WHERE expires <= ?
`

func (q *Queries) ExpireLogins(ctx context.Context, expires int64) error {
	_, err := q.db.ExecContext(ctx, expireLogins, expires)
	return err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (id, user_id, data) VALUES (?, ?, ?)
`

type InsertCredentialParams struct {
	ID     []byte
	UserID string
	Data   []byte
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertCredential, arg.ID, arg.UserID, arg.Data)
	return err
}

const insertLogin = `-- name: InsertLogin :exec
INSERT INTO logins (id, user_id, credential_id, secret_hash, expires, kind, client_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLoginParams struct {
	ID           string
	UserID       string
	CredentialID []byte
	SecretHash   []byte
	Expires      int64
	Kind         string
	ClientID     string
}

func (q *Queries) InsertLogin(ctx context.Context, arg InsertLoginParams) error {
	_, err := q.db.ExecContext(ctx, insertLogin,
		arg.ID,
		arg.UserID,
		arg.CredentialID,
		arg.SecretHash,
		arg.Expires,
		arg.Kind,
		arg.ClientID,
	)
	return err
}

const invitation = `-- name: Invitation :one
SELECT users.id, users.name, users.disabled, users.generation FROM invitations JOIN users ON users.id = invitations.user_id
WHERE secret_hash = ? AND expires > ? AND disabled = 0
    AND invitations.generation = users.generation
`

type InvitationParams struct {
	SecretHash []byte
	Expires    int64
}

func (q *Queries) Invitation(ctx context.Context, arg InvitationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, invitation, arg.SecretHash, arg.Expires)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.Generation,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, disabled, generation FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Disabled,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const login = `-- name: Login :one
SELECT logins.id, logins.user_id, logins.kind, logins.client_id, logins.expires FROM logins
JOIN users ON users.id = logins.user_id
JOIN credentials ON credentials.id = logins.credential_id
WHERE secret_hash = ? AND expires > ? AND disabled = 0
`

type LoginParams struct {
	SecretHash []byte
	Expires    int64
}

type LoginRow struct {
	ID       string
	UserID   string
	Kind     string
	ClientID string
	Expires  int64
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (LoginRow, error) {
	row := q.db.QueryRowContext(ctx, login, arg.SecretHash, arg.Expires)
	var i LoginRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ClientID,
		&i.Expires,
	)
	return i, err
}

const loginByID = `-- name: LoginByID :one
SELECT logins.id, logins.user_id, logins.kind, logins.client_id, logins.expires FROM logins
JOIN users ON users.id = logins.user_id
JOIN credentials ON credentials.id = logins.credential_id
WHERE logins.id = ? AND expires > ? AND disabled = 0
`

type LoginByIDParams struct {
	ID      string
	Expires int64
}

type LoginByIDRow struct {
	ID       string
	UserID   string
	Kind     string
	ClientID string
	Expires  int64
}

func (q *Queries) LoginByID(ctx context.Context, arg LoginByIDParams) (LoginByIDRow, error) {
	row := q.db.QueryRowContext(ctx, loginByID, arg.ID, arg.Expires)
	var i LoginByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ClientID,
		&i.Expires,
	)
	return i, err
}

const nativeLogoutIdentity = `-- name: NativeLogoutIdentity :one
SELECT logins.id FROM logins
JOIN users ON users.id = logins.user_id
JOIN credentials ON credentials.id = logins.credential_id
WHERE secret_hash = ? AND kind = 'native' AND disabled = 0
`

func (q *Queries) NativeLogoutIdentity(ctx context.Context, secretHash []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, nativeLogoutIdentity, secretHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const putInvitation = `-- name: PutInvitation :execrows
INSERT INTO invitations (user_id, secret_hash, expires, generation)
SELECT id, ?, ?, generation FROM users WHERE id = ? AND disabled = 0
ON CONFLICT (user_id) DO UPDATE SET secret_hash = excluded.secret_hash,
    expires = excluded.expires, generation = excluded.generation
`

type PutInvitationParams struct {
	SecretHash []byte
	Expires    int64
	ID         string
}

func (q *Queries) PutInvitation(ctx context.Context, arg PutInvitationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putInvitation, arg.SecretHash, arg.Expires, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserLogins = `-- name: RevokeUserLogins :exec
DELETE FROM logins WHERE user_id = ?
`

func (q *Queries) RevokeUserLogins(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeUserLogins, userID)
	return err
}

const setUserState = `-- name: SetUserState :exec
UPDATE users SET disabled = ?, generation = generation + 1 WHERE id = ?
`

type SetUserStateParams struct {
	Disabled int64
	ID       string
}

func (q *Queries) SetUserState(ctx context.Context, arg SetUserStateParams) error {
	_, err := q.db.ExecContext(ctx, setUserState, arg.Disabled, arg.ID)
	return err
}

const updateCredential = `-- name: UpdateCredential :execrows
UPDATE credentials SET data = ?, version = version + 1
WHERE id = ? AND user_id = ? AND version = ?
`

type UpdateCredentialParams struct {
	Data    []byte
	ID      []byte
	UserID  string
	Version int64
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredential,
		arg.Data,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userByID = `-- name: UserByID :one
SELECT id, name, disabled, generation FROM users WHERE id = ?
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.Generation,
	)
	return i, err
}

const userByName = `-- name: UserByName :one
SELECT id, name, disabled, generation FROM users WHERE name = ?
`

func (q *Queries) UserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Disabled,
		&i.Generation,
	)
	return i, err
}
